import requests
from openai import OpenAI
from dotenv import load_dotenv
import os
import json

load_dotenv()

client = OpenAI(
    api_key=os.environ["OPENAI_API_KEY"]
)

tools = [
    # each of these are functions
    {
        "type": "function",
        "name": "send_otp",
        "description": "This function sends the otp verification code to the user using the email address",
        "parameters": {
            "type": "object",
            "properties": {
                "email_address": {
                    "type": "string",
                    "description": "user email address input",
                },
            },
            "required": ["email_address"]
        },
    },
    {
        "type": "function",
        "name": "verify_otp",
        "description": "This function verifies the otp verification code using the verification code the user submitted",
        "parameters": {
            "type": "object",
            "properties": {
                "verification_code": {
                    "type": "string",
                    "description": "user verification code input",
                },
            },
            "required": ["verification_code"]
        },
    }
]


def generate_response(query):
    input_list = [
        {"role":"user","content":query}
    ]

    response = client.responses.create(
        model="gpt-5",
        tools=tools,
        input=input_list,
    )

    input_list += response.output
    print("Input List with AI response (possibly tools)")
    print(input_list)
    
    for item in response.output:
        if item.type == "function_call":
            if item.name == "send_otp":
                opt_output = send_otp(json.loads(item.arguments))
                
                input_list.append({
                    "type": "function_output",
                    "call_id": item.call_id,
                    "output": json.dumps({
                                "otp_output": opt_output
                              })
                })


    response = client.responses.create(
        model="gpt-5",
        instructions="Respond only with a horoscope generated by a tool.",
        tools=tools,
        input=input_list,
    )
    print(response)


def send_otp(email_address:str)->str:
    url="http://localhost/laravel/public/api/request_otp"
    response = requests.post(url)
    print(response.json())
    if response.json()['success'] == True:
        return f"Your verification code was sent to {email_address}. Enter the verification code here (expires: 30 sec.)"
    else:
        return f"Your verification code was not sent to {email_address}. Re-enter correct email address"


def verify_otp(verification_code:str)->str:
    url="http://localhost/laravel/public/api/request_verify_otp"
    data = {
        "verification_code":verification_code
    }
    response = requests.post(url, data=data)

    if response:
        return f"Account successfully created."
    else:
        return f"Account unsuccessfully created."

if __name__ == "__main__":
    print("Entering main")
    query = "My email address is basil_anton@yahoo.ca"
    generate_response(query)
